name: "Check Team Membership in GH Organisation"
author: "Igor Pecovnik"
description: "Team check"
inputs:
  ORG_MEMBERS:
    required: true
  GITHUB_TOKEN:
    required: true
runs:
  using: "composite"
  steps:
   -  uses: tspascoal/get-user-teams-membership@v2
       id: checkUserMember
       with:
         username: ${{ github.actor }}
         organization: armbian
         team: "Release manager"
         GITHUB_TOKEN: ${{ secrets.ORG_MEMBERS }}

    - name: Cancel if not a part of the team
      if: ${{ steps.checkUserMember.outputs.isTeamMember == 'false' }}
      uses: "andymckay/cancel-action@0.3"
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  
