name: "Collect data"
author: "Igor Pecovnik"
inputs:
  kernel-target:
    required: true
description: ""
runs:
  using: "composite"
  steps:

      - name: "Iperf test"
        shell: bash 
        run: |

          while :
          do
            IPERF=$(timeout 1000 ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "iperf3 -c 10.0.40.2 -t 5 -J 2>/dev/null | jq '.intervals[] .sum .bits_per_second' | LC_ALL=C datamash median 1 | cut -d"-" -f2" | LC_ALL=C awk '{$1/=1048576;printf "%.0f\n",$1}')
            if [[ -n "${IPERF}" ]] ; then
              echo "IPERF=${IPERF}" >> $GITHUB_ENV
              break
            fi
            echo "The server is busy running a test"
            sleep 2
          done

      - name: "7Zip benchmark"
        shell: bash         
        run: |

            SEVENZIP=$(timeout 1000 ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "7z b | grep 'Tot:' | awk '{print \$NF}'")
            if [[ -n "${SEVENZIP}" ]] ; then
              echo "SEVENZIP=${SEVENZIP}" >> $GITHUB_ENV
            fi

      - name: "Read kernel and U-boot"
        shell: bash         
        run: |

          echo "KERNEL=$(ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "uname -r" || true)" >> $GITHUB_ENV
          # read u-boot
          root_uuid=$(ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "sed -e 's/^.*root=//' -e 's/ .*$//' < /proc/cmdline" || true)
          root_partition_device=$(ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "blkid | tr -d '\":' | grep \"${root_uuid}\" | awk '{print \$1}' | rev | cut -c3- | rev" || true)
          echo "UBOOT=$(ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "dd status=none if=${root_partition_device} count=5000 | strings | grep armbian | grep U-Boot | tail -1 | grep -P \"[0-9]{4}.[0-9]{2}\" -o")" >> $GITHUB_ENV

      - name: "Collecing"
        shell: bash 
        run: |

          ARMBIAN_MONITOR=$(ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "armbianmonitor -u | grep -Eo 'https://[^ >]+'" || true)
          cat <<- EOD >> data-"${{ env.DUT_IP }}"-"${{ env.DUT_SLUG }}".parts
          {
            "dut_ip" : "${{ env.DUT_IP }}",
            "board_name" : "${{ env.BOARD_NAME }}",
            "u-boot" : "${{ env.UBOOT }}",
            "kernel" : "${{ env.KERNEL }}",
            "iperf" : "${{ env.IPERF }}",
            "sevenzip" : "${{ env.SEVENZIP }}",
            "armbian_monitor" : "${ARMBIAN_MONITOR}",
            "kernel_target" : "${{ inputs.kernel-target }}"
          },
          EOD
      
      - name: Upload JSON
        uses: actions/upload-artifact@v3
        with:
          name: JSON
          path: data-*.*
