name: "Collect data"
author: "Igor Pecovnik"
inputs:
  kernel_target:
    required: true
description: ""
runs:
  using: "composite"
  steps:

      - name: "Collecing"
        shell: bash 
        run: |
        
          ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "run-parts /etc/update-motd.d/" || true
          ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "dmesg --color=always" || true
          ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "dpkg --configure -a; apt-get -y install binutils iperf3 neofetch datamash p7zip-full" || true
          ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "neofetch" || true

          while :
          do
            IPERF=$(timeout 1000 ssh -i /tmp/${{ env.RANDOM }} -o StrictHostKeyChecking=no root@${{ env.DUT_IP }} "iperf3 -c 10.0.40.2 -t 5 -J 2>/dev/null | jq '.intervals[] .sum .bits_per_second' | LC_ALL=C datamash median 1 | cut -d"-" -f2" | LC_ALL=C awk '{$1/=1048576;printf "%.0f\n",$1}')
            if [[ -n "${IPERF}" ]] ; then
              echo "IPERF=${IPERF}" >> $GITHUB_ENV
              break
            fi
            echo "The server is busy running a test"
            sleep 2
          done

      - name: "Collecing"
        shell: bash 
        run: |
          cat <<- EOD >> json
          {
            "dut_ip" : "${{ env.DUT_IP }}",
            "board_name" : "${{ env.BOARD_NAME }}",
            "kernel_target" : "${{ inputs.kernel_target }}"
          },
          EOD
      
      - name: Upload JSON
        uses: actions/upload-artifact@v3
        with:
          name: json
